// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
)

type Album struct {
	ID        sql.NullInt64
	Title     string
	Year      sql.NullInt64
	Rating    sql.NullInt64
	DateAdded int64
}

type AlbumsArtist struct {
	AlbumID  sql.NullInt64
	ArtistID sql.NullInt64
}

type Artist struct {
	ID   sql.NullInt64
	Name string
}
